module.exports.UNIT_LIST = [
    { unit_id: 'unit01', unit_name: 'Kilogram', abbreviation: 'kg' },
    { unit_id: 'unit02', unit_name: 'Gram', abbreviation: 'g' },
    { unit_id: 'unit03', unit_name: 'Meter', abbreviation: 'm' },
    { unit_id: 'unit04', unit_name: 'Centimeter', abbreviation: 'cm' },
    { unit_id: 'unit05', unit_name: 'Millimeter', abbreviation: 'mm' },
    { unit_id: 'unit06', unit_name: 'Liter', abbreviation: 'L' },
    { unit_id: 'unit07', unit_name: 'Milliliter', abbreviation: 'mL' },
    { unit_id: 'unit08', unit_name: 'Square Meter', abbreviation: 'm²' },
    { unit_id: 'unit09', unit_name: 'Cubic Meter', abbreviation: 'm³' },
    { unit_id: 'unit10', unit_name: 'Inch', abbreviation: 'in' },
    { unit_id: 'unit11', unit_name: 'Foot', abbreviation: 'ft' },
    { unit_id: 'unit12', unit_name: 'Yard', abbreviation: 'yd' },
    { unit_id: 'unit13', unit_name: 'Square Foot', abbreviation: 'ft²' },
    { unit_id: 'unit14', unit_name: 'Square Inch', abbreviation: 'in²' },
    { unit_id: 'unit15', unit_name: 'Gallon', abbreviation: 'gal' },
    { unit_id: 'unit16', unit_name: 'Pint', abbreviation: 'pt' },
    { unit_id: 'unit17', unit_name: 'Quart', abbreviation: 'qt' },
    { unit_id: 'unit18', unit_name: 'Ton', abbreviation: 't' },
    { unit_id: 'unit19', unit_name: 'Pound', abbreviation: 'lb' },
    { unit_id: 'unit20', unit_name: 'Ounce', abbreviation: 'oz' },
];
